apiVersion: v1
kind: Service
metadata:
  name: expense-predictor-service  
spec:
  selector:
    app: expense-predictor        
  ports:
    - protocol: TCP
      port: 80                     
      targetPort: 5000             
  type: LoadBalancer              