apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-predictor
  template:
    metadata:
      labels:
        app: expense-predictor
    spec:
      imagePullSecrets:  # Add this block
      - name: dockerhub-secret
      containers:
      - name: flask-app
        image: ameyhiremath/personal-expense-predictor:final
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
