name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ameyav.btech23@rvu.edu.in }}
        password: ${{ secrets.Amey@270204 }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.ameyav.btech23@rvu.edu.in }}/expense-predictor:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.ameyav.btech23@rvu.edu.in }}/expense-predictor:latest
